### ISSUE TITLE
boostrap trandoshan locally don't have dashboard

### ISSUE THREAD

**Issue by yalarmorghulis** [trandoshan-io/trandoshan-parent#1]
Hi there, 

trandoshan-io project is really promising, thanks for you great job.  When I try to bootstrap trandoshan locally,  I have no idea how to explore the features, it seems there is not dashboard include locally,  can you fix it ?  Thanks.

**Comment by creekorful** [comment]
Hello,

First of all thank you!

You are right. Currently the way to access the dashboard is by running ``ng serve --aot`` from the project directory. (You will need npm and angular/cli installed).

It is wanted to not have a dashboard image publicly available on dockerhub since the API url (found in angular environment config file) depend on your trandoshan installation. (And cannot be configured at runtime)

But yes I could make it work in local since the API is always accessible at localhost:15002. I will add a Dockerfile in dashboard project and add it to the docker-compose.

**Comment by creekorful** [comment]
Dashboard is now included in the project.
