### ISSUE TITLE
dashboard missing

### ISSUE THREAD

**Issue by ghost** [trandoshan-io/trandoshan-parent#4]
Hi,

Hope you are all well !

While executing ./bootstrap.sh, I have the following error:

```bash
Pulling dashboard (trandoshanio/dashboard:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling dashboard (trandoshanio/dashboard:)...
ERROR: pull access denied for trandoshanio/dashboard, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Can you make it public ?

Cheers,
X

**Comment by creekorful** [comment]
Hello !

It is wanted to not have a dashboard image publicly available since the API url (found in angular environment config file) depend on your trandoshan installation. (And cannot be configured at runtime)

What you can do to make this work is running the **build.sh** script it will build all projects locally.

Then you'll just need to run **bootstrap.sh** to start the Crawler.

Have a good day !

**Comment by ghost** [comment]
That s what I did, thanks. You made an amazing work.

For a smoother and more golang oriented admin, I would recommend you https://github.com/qor/admin

ps. have you noticed that your twitter account is suspended ?
